"""Universal AIAT worker contract and adapter SDK.

The worker contract is deliberately independent of any runtime implementation.
It is the payload contract carried by :class:`MessageEnvelope`; the router,
flow controller, and tool service remain the authoritative control-plane
components.
"""

from .models import (
    CONTRACT_VERSION,
    ADAPTER_API_VERSION,
    ArtifactKind,
    CapabilityRequirement,
    WorkerCapabilityRequirement,
    CheckpointMode,
    CancellationMode,
    ContractError,
    EventType,
    MemoryMode,
    ModelMode,
    ModelProfileReference,
    ProtocolVersion,
    RuntimeExtension,
    StreamingMode,
    ToolMode,
    WorkerArtifact,
    WorkerAuditEvent,
    WorkerCapabilities,
    WorkerCancellation,
    WorkerCheckpoint,
    WorkerError,
    WorkerEvent,
    WorkerHealth,
    WorkerIdentity,
    WorkerManifest,
    WorkerPause,
    WorkerProgress,
    WorkerReadiness,
    WorkerResult,
    WorkerResume,
    WorkerRunAccepted,
    WorkerRunRequest,
    WorkerToolRequest,
    WorkerToolResponse,
    WorkerUsage,
    WorkspaceMode,
)
from .protocol import (
    CURRENT_MAJOR,
    CURRENT_PROTOCOL_VERSION,
    ProtocolNegotiationError,
    ProtocolNegotiationResult,
    negotiate_protocol,
)
from .adapters import (
    AdapterContext,
    BaseWorkerAdapter,
    NativeWorkerAdapter,
    WorkerAdapter,
)
from .conformance import ConformanceReport, ConformanceRunner, ConformanceTestResult
from .controller import (
    RUN_TRANSITIONS,
    TERMINAL_RUN_STATES,
    WorkerRunController,
    WorkerRunError,
    WorkerRunOutcome,
)

__all__ = [
    "ADAPTER_API_VERSION",
    "CONTRACT_VERSION",
    "CURRENT_MAJOR",
    "CURRENT_PROTOCOL_VERSION",
    "AdapterContext",
    "ArtifactKind",
    "BaseWorkerAdapter",
    "CapabilityRequirement",
    "WorkerCapabilityRequirement",
    "CancellationMode",
    "CheckpointMode",
    "ConformanceReport",
    "ConformanceRunner",
    "ConformanceTestResult",
    "RUN_TRANSITIONS",
    "TERMINAL_RUN_STATES",
    "ContractError",
    "EventType",
    "MemoryMode",
    "ModelMode",
    "ModelProfileReference",
    "NativeWorkerAdapter",
    "ProtocolNegotiationError",
    "ProtocolNegotiationResult",
    "ProtocolVersion",
    "RuntimeExtension",
    "StreamingMode",
    "ToolMode",
    "WorkerAdapter",
    "WorkerArtifact",
    "WorkerAuditEvent",
    "WorkerCapabilities",
    "WorkerCancellation",
    "WorkerCheckpoint",
    "WorkerError",
    "WorkerEvent",
    "WorkerHealth",
    "WorkerIdentity",
    "WorkerManifest",
    "WorkerPause",
    "WorkerProgress",
    "WorkerReadiness",
    "WorkerResult",
    "WorkerResume",
    "WorkerRunAccepted",
    "WorkerRunController",
    "WorkerRunError",
    "WorkerRunRequest",
    "WorkerRunOutcome",
    "WorkerToolRequest",
    "WorkerToolResponse",
    "WorkerUsage",
    "WorkspaceMode",
    "negotiate_protocol",
]
