from enum import StrEnum


class ProjectState(StrEnum):
    """Project workflow states defined by org architecture section 11.2."""

    INIT = "INIT"
    FEASIBILITY_CHECK = "FEASIBILITY_CHECK"
    FEASIBILITY_REPORT = "FEASIBILITY_REPORT"
    PDR_CREATION = "PDR_CREATION"
    PDR_REVIEW = "PDR_REVIEW"
    SECURITY_BLOCKED = "SECURITY_BLOCKED"
    CDR_CREATION = "CDR_CREATION"
    CDR_REVIEW = "CDR_REVIEW"
    HUMAN_APPROVAL = "HUMAN_APPROVAL"
    RR_CREATION = "RR_CREATION"
    SPRINT_PLANNING = "SPRINT_PLANNING"
    INFRA_PROVISIONING = "INFRA_PROVISIONING"
    IN_PROGRESS = "IN_PROGRESS"
    RETROSPECTIVE = "RETROSPECTIVE"
    KPI_PERSISTENCE = "KPI_PERSISTENCE"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"
