"""Create the private AIAT identity-service schema.

All sensitive values are represented as opaque references or cryptographic
hashes.  No plaintext password, API key, SMTP credential, cookie, OAuth
refresh token, TOTP seed, or recovery code column is created.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "0001_identity_control_plane"
down_revision = None
branch_labels = None
depends_on = None


def _id() -> sa.Column:
    return sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))


def _timestamps() -> list[sa.Column]:
    return [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table("email_domains", _id(), sa.Column("domain", sa.Text(), nullable=False, unique=True), sa.Column("state", sa.Text(), nullable=False, server_default="PENDING_VERIFICATION"), sa.Column("provider_domain_id", sa.Text(), unique=True), sa.Column("verification_evidence", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("created_by", sa.Text(), nullable=False), *_timestamps(), sa.CheckConstraint("domain = lower(domain)"))
    op.create_table("agent_email_identities", _id(), sa.Column("company_id", UUID(as_uuid=True), nullable=False), sa.Column("worker_id", UUID(as_uuid=True), nullable=False, unique=True), sa.Column("domain_id", UUID(as_uuid=True), sa.ForeignKey("email_domains.id", ondelete="RESTRICT"), nullable=False), sa.Column("address", sa.Text(), nullable=False, unique=True), sa.Column("friendly_alias", sa.Text(), unique=True), sa.Column("state", sa.Text(), nullable=False), sa.Column("quota_mb", sa.Integer(), nullable=False, server_default="100"), sa.Column("outbound_enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("provider_account_id", sa.Text(), unique=True), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("state_evidence", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), *_timestamps(), sa.UniqueConstraint("company_id", "worker_id", name="uq_agent_identity_company_worker"), sa.UniqueConstraint("id", "worker_id", name="uq_agent_identity_id_worker"), sa.CheckConstraint("quota_mb > 0"), sa.CheckConstraint("state IN ('HIRED_PENDING_IDENTITY', 'TEMPORARY_MAILBOX_APPROVAL_PENDING', 'IDENTITY_PROVISIONING', 'IDENTITY_VERIFYING', 'IDENTITY_ACTIVE', 'IDENTITY_PROVISIONING_FAILED', 'SUSPENDED', 'ARCHIVED')", name="ck_agent_identity_state"))
    op.create_index("ix_agent_email_identities_state", "agent_email_identities", ["state"])
    op.create_table("email_aliases", _id(), sa.Column("identity_id", UUID(as_uuid=True), sa.ForeignKey("agent_email_identities.id", ondelete="CASCADE"), nullable=False), sa.Column("address", sa.Text(), nullable=False, unique=True), sa.Column("state", sa.Text(), nullable=False, server_default="ACTIVE"), *_timestamps())
    op.create_table("mailbox_provisioning_jobs", _id(), sa.Column("identity_id", UUID(as_uuid=True), sa.ForeignKey("agent_email_identities.id", ondelete="CASCADE")), sa.Column("company_id", UUID(as_uuid=True), nullable=False), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("state", sa.Text(), nullable=False), sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("provider_correlation_id", sa.Text()), sa.Column("evidence", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), *_timestamps(), sa.UniqueConstraint("company_id", "worker_id", name="uq_mailbox_job_company_worker"))
    op.create_table("mail_events", _id(), sa.Column("identity_id", UUID(as_uuid=True), sa.ForeignKey("agent_email_identities.id", ondelete="CASCADE"), nullable=False), sa.Column("provider_message_id", sa.Text()), sa.Column("event_type", sa.Text(), nullable=False), sa.Column("metadata_json", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("identity_id", "provider_message_id", "event_type", name="uq_mail_event_provider"))
    op.create_index("ix_mail_events_identity_occurred", "mail_events", ["identity_id", "occurred_at"])
    op.create_table("mail_verification_transactions", _id(), sa.Column("identity_id", UUID(as_uuid=True), sa.ForeignKey("agent_email_identities.id", ondelete="CASCADE"), nullable=False), sa.Column("provider_message_id", sa.Text()), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("code_hash", sa.String(64)), sa.Column("link_hash", sa.String(64)), sa.Column("state", sa.Text(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), *_timestamps())
    op.create_table("outbound_mail_requests", _id(), sa.Column("identity_id", UUID(as_uuid=True), nullable=False), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("sender", sa.Text(), nullable=False), sa.Column("recipients_json", JSONB(), nullable=False), sa.Column("recipient_class", sa.Text(), nullable=False), sa.Column("subject", sa.Text(), nullable=False), sa.Column("content_ref", sa.Text(), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("state", sa.Text(), nullable=False), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("provider_message_id", sa.Text(), unique=True), sa.Column("provider_correlation_id", sa.Text()), *_timestamps(), sa.ForeignKeyConstraint(["identity_id", "worker_id"], ["agent_email_identities.id", "agent_email_identities.worker_id"], ondelete="RESTRICT", name="fk_outbound_identity_owner"))
    op.create_index("ix_outbound_mail_requests_worker_state", "outbound_mail_requests", ["worker_id", "state"])
    op.create_table("outbound_delivery_attempts", _id(), sa.Column("outbound_request_id", UUID(as_uuid=True), sa.ForeignKey("outbound_mail_requests.id", ondelete="CASCADE"), nullable=False), sa.Column("attempt_number", sa.Integer(), nullable=False), sa.Column("provider_correlation_id", sa.Text()), sa.Column("provider_message_id", sa.Text()), sa.Column("outcome", sa.Text(), nullable=False), sa.Column("failure_class", sa.Text()), sa.Column("sanitized_reason", sa.Text()), sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.UniqueConstraint("outbound_request_id", "attempt_number", name="uq_outbound_attempt"))
    op.create_table("identity_event_outbox", _id(), sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False, unique=True), sa.Column("event_type", sa.Text(), nullable=False), sa.Column("aggregate_type", sa.Text(), nullable=False), sa.Column("aggregate_id", sa.Text(), nullable=False), sa.Column("payload_json", JSONB(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("published_at", sa.DateTime(timezone=True)))
    op.create_index("ix_identity_event_outbox_sequence", "identity_event_outbox", ["sequence"])
    op.create_table("identity_client_registrations", _id(), sa.Column("client_id", sa.Text(), nullable=False, unique=True), sa.Column("public_key", sa.Text(), nullable=False), sa.Column("scopes", JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")), sa.Column("state", sa.Text(), nullable=False, server_default="ACTIVE"), *_timestamps())
    op.create_table("identity_client_nonces", sa.Column("client_id", sa.Text(), nullable=False), sa.Column("nonce", sa.Text(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.PrimaryKeyConstraint("client_id", "nonce"))
    op.create_index("ix_identity_client_nonces_expiry", "identity_client_nonces", ["expires_at"])
    op.create_table("identity_client_cursors", _id(), sa.Column("client_id", sa.Text(), nullable=False, unique=True), sa.Column("last_sequence", sa.BigInteger(), nullable=False, server_default="0"), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_table("external_accounts", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("identity_id", UUID(as_uuid=True), nullable=False), sa.Column("service", sa.Text(), nullable=False), sa.Column("service_category", sa.Text(), nullable=False), sa.Column("state", sa.Text(), nullable=False), sa.Column("credential_ref", sa.Text(), nullable=False), sa.Column("browser_profile_ref", sa.Text(), nullable=False), sa.Column("approval_id", UUID(as_uuid=True), nullable=False), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), *_timestamps(), sa.UniqueConstraint("worker_id", "service", name="uq_external_account_worker_service"), sa.UniqueConstraint("id", "worker_id", name="uq_external_account_id_worker"), sa.ForeignKeyConstraint(["identity_id", "worker_id"], ["agent_email_identities.id", "agent_email_identities.worker_id"], ondelete="RESTRICT", name="fk_external_account_identity_owner"), sa.CheckConstraint("state IN ('REQUESTED', 'ACTIVE', 'SUSPENDED', 'CLOSED')", name="ck_external_account_state"))
    op.create_table("credential_leases", _id(), sa.Column("external_account_id", UUID(as_uuid=True), nullable=False), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("lease_hash", sa.String(64), nullable=False, unique=True), sa.Column("scope", sa.Text(), nullable=False), sa.Column("state", sa.Text(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("used_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.ForeignKeyConstraint(["external_account_id", "worker_id"], ["external_accounts.id", "external_accounts.worker_id"], ondelete="CASCADE", name="fk_credential_lease_account_owner"), sa.CheckConstraint("state IN ('ACTIVE', 'CONSUMED', 'REVOKED', 'EXPIRED')", name="ck_credential_lease_state"))
    op.create_index("ix_credential_leases_worker_expiry", "credential_leases", ["worker_id", "expires_at"])
    op.create_table("browser_auth_sessions", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("external_account_id", UUID(as_uuid=True), nullable=False), sa.Column("service", sa.Text(), nullable=False), sa.Column("profile_ref", sa.Text(), nullable=False), sa.Column("state", sa.Text(), nullable=False), sa.Column("lease_version", sa.Integer(), nullable=False, server_default="1"), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), *_timestamps(), sa.UniqueConstraint("worker_id", "service", "profile_ref", name="uq_browser_session_profile"), sa.ForeignKeyConstraint(["external_account_id", "worker_id"], ["external_accounts.id", "external_accounts.worker_id"], ondelete="CASCADE", name="fk_browser_session_account_owner"), sa.CheckConstraint("state IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name="ck_browser_session_state"), sa.CheckConstraint("lease_version > 0", name="ck_browser_session_lease_version"))
    op.create_table("identity_approval_requests", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("kind", sa.Text(), nullable=False), sa.Column("target_id", UUID(as_uuid=True), nullable=False), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("state", sa.Text(), nullable=False), sa.Column("decided_by", sa.Text()), sa.Column("reason", sa.Text()), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_index("ix_identity_approvals_target", "identity_approval_requests", ["target_id", "state"])
    op.create_table("identity_usage_events", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("kind", sa.Text(), nullable=False), sa.Column("units", sa.BigInteger(), nullable=False), sa.Column("hold_id", UUID(as_uuid=True)), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), sa.Column("metadata_json", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.CheckConstraint("units > 0", name="ck_identity_usage_units"))
    op.create_table("identity_audit_events", _id(), sa.Column("actor_id", sa.Text(), nullable=False), sa.Column("action", sa.Text(), nullable=False), sa.Column("target_type", sa.Text(), nullable=False), sa.Column("target_id", sa.Text(), nullable=False), sa.Column("outcome", sa.Text(), nullable=False), sa.Column("metadata_json", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_index("ix_identity_audit_target", "identity_audit_events", ["target_type", "target_id", "occurred_at"])
    op.create_table("identity_provider_rates", _id(), sa.Column("provider", sa.Text(), nullable=False), sa.Column("rate_key", sa.Text(), nullable=False), sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("count", sa.Integer(), nullable=False, server_default="0"), sa.UniqueConstraint("provider", "rate_key", "window_started_at", name="uq_identity_provider_rate"), sa.CheckConstraint("count >= 0", name="ck_identity_provider_rate_count"))
    op.create_table("identity_budget_holds", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("kind", sa.Text(), nullable=False), sa.Column("units", sa.BigInteger(), nullable=False), sa.Column("state", sa.Text(), nullable=False), sa.Column("idempotency_key", sa.Text(), nullable=False, unique=True), *_timestamps(), sa.CheckConstraint("units > 0", name="ck_identity_budget_hold_units"), sa.CheckConstraint("state IN ('RESERVED', 'COMMITTED', 'RELEASED')", name="ck_identity_budget_hold_state"))
    op.create_foreign_key("fk_identity_usage_hold", "identity_usage_events", "identity_budget_holds", ["hold_id"], ["id"], ondelete="RESTRICT")
    op.create_table("identity_state_transitions", _id(), sa.Column("identity_id", UUID(as_uuid=True), sa.ForeignKey("agent_email_identities.id", ondelete="CASCADE"), nullable=False), sa.Column("from_state", sa.Text()), sa.Column("to_state", sa.Text(), nullable=False), sa.Column("evidence", JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("actor_id", sa.Text()), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_table("identity_access_grants", _id(), sa.Column("worker_id", UUID(as_uuid=True), nullable=False), sa.Column("identity_id", UUID(as_uuid=True), nullable=False), sa.Column("grant_type", sa.Text(), nullable=False), sa.Column("state", sa.Text(), nullable=False, server_default="ACTIVE"), sa.Column("issued_by", sa.Text(), nullable=False), *_timestamps(), sa.UniqueConstraint("worker_id", "identity_id", "grant_type", name="uq_identity_access_grant"), sa.ForeignKeyConstraint(["identity_id", "worker_id"], ["agent_email_identities.id", "agent_email_identities.worker_id"], ondelete="CASCADE", name="fk_identity_access_grant_owner"), sa.CheckConstraint("state IN ('ACTIVE', 'REVOKED')", name="ck_identity_access_grant_state"))
    op.create_foreign_key("fk_external_account_approval", "external_accounts", "identity_approval_requests", ["approval_id"], ["id"], ondelete="RESTRICT")


def downgrade() -> None:
    for table in ["identity_access_grants", "identity_state_transitions", "identity_usage_events", "identity_budget_holds", "identity_provider_rates", "identity_audit_events", "browser_auth_sessions", "credential_leases", "external_accounts", "identity_approval_requests", "identity_client_cursors", "identity_client_nonces", "identity_client_registrations", "identity_event_outbox", "outbound_delivery_attempts", "outbound_mail_requests", "mail_verification_transactions", "mail_events", "mailbox_provisioning_jobs", "email_aliases", "agent_email_identities", "email_domains"]:
        op.drop_table(table)
