# AUTO-GENERATED. DO NOT EDIT.
# Generated by sync_free_models.py

FREE_OPENROUTER_MODELS = [{'active': True,
  'api_model_name': 'arcee-ai/trinity-large-preview:free',
  'best_for': ['creative-writing', 'agentic-workflows', 'tool-calling'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Trinity-Large-Preview is a frontier-scale open-weight language model from Arcee, '
                 'built as a 400B-parameter sparse Mixture-of-Experts with 13B active parameters '
                 'per token using 4-of-256 expert routing. \n'
                 '\n'
                 'It excels in creative writing, storytelling, role-play, chat scenarios, and '
                 'real-time voice assistance, better than your average reasoning model usually '
                 'can. But we’re also introducing some of our newer agentic performance. It was '
                 'trained to navigate well in agent harnesses like OpenCode, Cline, and Kilo Code, '
                 'and to handle complex toolchains and long, constraint-filled prompts. \n'
                 '\n'
                 'The architecture natively supports very long context windows up to 512k tokens, '
                 'with the Preview API currently served at 128k context using 8-bit quantization '
                 'for practical deployment. Trinity-Large-Preview reflects Arcee’s '
                 'efficiency-first design philosophy, offering a production-oriented frontier '
                 'model with open weights and permissive licensing suitable for real-world '
                 'applications and experimentation.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'moe-model'],
  'max_context_tokens': 131000,
  'missing_syncs': 0,
  'model_id': 'openrouter/arcee-ai/trinity-large-preview:free',
  'name': 'Arcee AI: Trinity Large Preview (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['max_tokens',
                           'response_format',
                           'structured_outputs',
                           'temperature',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'arcee-ai/trinity-mini:free',
  'best_for': ['fast-reasoning', 'tool-calling', 'lightweight-analysis'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Trinity Mini is a 26B-parameter (3B active) sparse mixture-of-experts language '
                 'model featuring 128 experts with 8 active per token. Engineered for efficient '
                 'reasoning over long contexts (131k) with robust function calling and multi-step '
                 'agent workflows.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'compact-model'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/arcee-ai/trinity-mini:free',
  'name': 'Arcee AI: Trinity Mini (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'response_format',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Venice Uncensored Dolphin Mistral 24B Venice Edition is a fine-tuned variant of '
                 'Mistral-Small-24B-Instruct-2501, developed by dphn.ai in collaboration with '
                 'Venice.ai. This model is designed as an “uncensored” instruct-tuned LLM, '
                 'preserving user control over alignment, system prompts, and behavior. Intended '
                 'for advanced and unrestricted use cases, Venice Uncensored emphasizes '
                 'steerability and transparent behavior, removing default safety and alignment '
                 'layers typically found in mainstream assistant models.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 32768,
  'missing_syncs': 0,
  'model_id': 'openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition:free',
  'name': 'Venice: Uncensored (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'response_format',
                           'stop',
                           'structured_outputs',
                           'temperature',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': False,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'google/gemma-3-12b-it:free',
  'best_for': ['general-conversation', 'multilingual', 'lightweight-tasks'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Gemma 3 introduces multimodality, supporting vision-language input and text '
                 'outputs. It handles context windows up to 128k tokens, understands over 140 '
                 'languages, and offers improved math, reasoning, and chat capabilities, including '
                 'structured outputs and function calling. Gemma 3 12B is the second largest in '
                 'the family of Gemma 3 models after [Gemma 3 27B](google/gemma-3-27b-it)',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['text', 'image'],
  'limits': ['free-tier-rate-limited', 'open-weight-model'],
  'max_context_tokens': 32768,
  'missing_syncs': 0,
  'model_id': 'openrouter/google/gemma-3-12b-it:free',
  'name': 'Google: Gemma 3 12B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['max_tokens', 'seed', 'stop', 'temperature', 'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'google/gemma-3-27b-it:free',
  'best_for': ['general-conversation', 'code-generation', 'multimodal-vision', 'multilingual'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Gemma 3 introduces multimodality, supporting vision-language input and text '
                 'outputs. It handles context windows up to 128k tokens, understands over 140 '
                 'languages, and offers improved math, reasoning, and chat capabilities, including '
                 "structured outputs and function calling. Gemma 3 27B is Google's latest open "
                 'source model, successor to [Gemma 2](google/gemma-2-27b-it)',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['text', 'image'],
  'limits': ['free-tier-rate-limited', 'open-weight-model'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/google/gemma-3-27b-it:free',
  'name': 'Google: Gemma 3 27B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['max_tokens', 'response_format', 'seed', 'stop', 'temperature', 'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'google/gemma-3-4b-it:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Gemma 3 introduces multimodality, supporting vision-language input and text '
                 'outputs. It handles context windows up to 128k tokens, understands over 140 '
                 'languages, and offers improved math, reasoning, and chat capabilities, including '
                 'structured outputs and function calling.',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['text', 'image'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 32768,
  'missing_syncs': 0,
  'model_id': 'openrouter/google/gemma-3-4b-it:free',
  'name': 'Google: Gemma 3 4B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['max_tokens', 'response_format', 'seed', 'stop', 'temperature', 'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'google/gemma-3n-e2b-it:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Gemma 3n E2B IT is a multimodal, instruction-tuned model developed by Google '
                 'DeepMind, designed to operate efficiently at an effective parameter size of 2B '
                 'while leveraging a 6B architecture. Based on the MatFormer architecture, it '
                 'supports nested submodels and modular composition via the Mix-and-Match '
                 'framework. Gemma 3n models are optimized for low-resource deployment, offering '
                 '32K context length and strong multilingual and reasoning performance across '
                 'common benchmarks. This variant is trained on a diverse corpus including code, '
                 'math, web, and multimodal data.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 8192,
  'missing_syncs': 0,
  'model_id': 'openrouter/google/gemma-3n-e2b-it:free',
  'name': 'Google: Gemma 3n 2B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['max_tokens', 'response_format', 'seed', 'temperature', 'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'google/gemma-3n-e4b-it:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Gemma 3n E4B-it is optimized for efficient execution on mobile and low-resource '
                 'devices, such as phones, laptops, and tablets. It supports multimodal '
                 'inputs—including text, visual data, and audio—enabling diverse tasks such as '
                 'text generation, speech recognition, translation, and image analysis. Leveraging '
                 'innovations like Per-Layer Embedding (PLE) caching and the MatFormer '
                 'architecture, Gemma 3n dynamically manages memory usage and computational load '
                 'by selectively activating model parameters, significantly reducing runtime '
                 'resource requirements.\n'
                 '\n'
                 'This model supports a wide linguistic range (trained in over 140 languages) and '
                 'features a flexible 32K token context window. Gemma 3n can selectively load '
                 'parameters, optimizing memory and computational efficiency based on the task or '
                 'device capabilities, making it well-suited for privacy-focused, offline-capable '
                 'applications and on-device AI solutions. [Read more in the blog '
                 'post](https://developers.googleblog.com/en/introducing-gemma-3n/)',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 8192,
  'missing_syncs': 0,
  'model_id': 'openrouter/google/gemma-3n-e4b-it:free',
  'name': 'Google: Gemma 3n 4B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['max_tokens', 'response_format', 'seed', 'temperature', 'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': False,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'liquid/lfm-2.5-1.2b-instruct:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'LFM2.5-1.2B-Instruct is a compact, high-performance instruction-tuned model '
                 'built for fast on-device AI. It delivers strong chat quality in a 1.2B parameter '
                 'footprint, with efficient edge inference and broad runtime support.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 32768,
  'missing_syncs': 0,
  'model_id': 'openrouter/liquid/lfm-2.5-1.2b-instruct:free',
  'name': 'LiquidAI: LFM2.5-1.2B-Instruct (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'min_p',
                           'presence_penalty',
                           'repetition_penalty',
                           'seed',
                           'stop',
                           'temperature',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': False,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'liquid/lfm-2.5-1.2b-thinking:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'LFM2.5-1.2B-Thinking is a lightweight reasoning-focused model optimized for '
                 'agentic tasks, data extraction, and RAG—while still running comfortably on edge '
                 'devices. It supports long context (up to 32K tokens) and is designed to provide '
                 'higher-quality “thinking” responses in a small 1.2B model.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 32768,
  'missing_syncs': 0,
  'model_id': 'openrouter/liquid/lfm-2.5-1.2b-thinking:free',
  'name': 'LiquidAI: LFM2.5-1.2B-Thinking (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['frequency_penalty',
                           'include_reasoning',
                           'max_tokens',
                           'min_p',
                           'presence_penalty',
                           'reasoning',
                           'repetition_penalty',
                           'seed',
                           'stop',
                           'temperature',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'meta-llama/llama-3.2-3b-instruct:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Llama 3.2 3B is a 3-billion-parameter multilingual large language model, '
                 'optimized for advanced natural language processing tasks like dialogue '
                 'generation, reasoning, and summarization. Designed with the latest transformer '
                 'architecture, it supports eight languages, including English, Spanish, and '
                 'Hindi, and is adaptable for additional languages.\n'
                 '\n'
                 'Trained on 9 trillion tokens, the Llama 3.2 3B model excels in '
                 'instruction-following, complex reasoning, and tool use. Its balanced performance '
                 'makes it ideal for applications needing accuracy and efficiency in text '
                 'generation across multilingual settings.\n'
                 '\n'
                 'Click here for the [original model '
                 'card](https://github.com/meta-llama/llama-models/blob/main/models/llama3_2/MODEL_CARD.md).\n'
                 '\n'
                 "Usage of this model is subject to [Meta's Acceptable Use "
                 'Policy](https://www.llama.com/llama3/use-policy/).',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/meta-llama/llama-3.2-3b-instruct:free',
  'name': 'Meta: Llama 3.2 3B Instruct (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'stop',
                           'temperature',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'meta-llama/llama-3.3-70b-instruct:free',
  'best_for': ['general-conversation', 'code-generation', 'multilingual'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'meta-llama-license'],
  'default_temperature': 0.7,
  'description': 'The Meta Llama 3.3 multilingual large language model (LLM) is a pretrained and '
                 'instruction tuned generative model in 70B (text in/text out). The Llama 3.3 '
                 'instruction tuned text only model is optimized for multilingual dialogue use '
                 'cases and outperforms many of the available open source and closed chat models '
                 'on common industry benchmarks.\n'
                 '\n'
                 'Supported languages: English, German, French, Italian, Portuguese, Hindi, '
                 'Spanish, and Thai.\n'
                 '\n'
                 '[Model '
                 'Card](https://github.com/meta-llama/llama-models/blob/main/models/llama3_3/MODEL_CARD.md)',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 65536,
  'missing_syncs': 0,
  'model_id': 'openrouter/meta-llama/llama-3.3-70b-instruct:free',
  'name': 'Meta: Llama 3.3 70B Instruct (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'stop',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': False,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'minimax/minimax-m2.5:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'MiniMax-M2.5 is a SOTA large language model designed for real-world '
                 'productivity. Trained in a diverse range of complex real-world digital working '
                 'environments, M2.5 builds upon the coding expertise of M2.1 to extend into '
                 'general office work, reaching fluency in generating and operating Word, Excel, '
                 'and Powerpoint files, context switching between diverse software environments, '
                 'and working across different agent and human teams. Scoring 80.2% on SWE-Bench '
                 'Verified, 51.3% on Multi-SWE-Bench, and 76.3% on BrowseComp, M2.5 is also more '
                 'token efficient than previous generations, having been trained to optimize its '
                 'actions and output through planning.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 196608,
  'missing_syncs': 0,
  'model_id': 'openrouter/minimax/minimax-m2.5:free',
  'name': 'MiniMax: MiniMax M2.5 (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'response_format',
                           'seed',
                           'stop',
                           'temperature',
                           'tools'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': False,
  'api_model_name': 'mistralai/mistral-small-3.1-24b-instruct:free',
  'best_for': ['code-generation', 'tool-calling', 'multilingual', 'vision'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Mistral Small 3.1 24B Instruct via OpenRouter (free). 24B multimodal model with '
                 '128 k context. Strong coding, function calling, and multilingual support.',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['text', 'image'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 128000,
  'missing_syncs': 1,
  'model_id': 'openrouter/mistralai/mistral-small-3.1-24b-instruct:free',
  'name': 'Mistral Small 3.1 24B Instruct',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['tools', 'stream'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': False,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'nousresearch/hermes-3-llama-3.1-405b:free',
  'best_for': ['general-conversation', 'tool-calling', 'multi-turn-reasoning'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'llama-license'],
  'default_temperature': 0.7,
  'description': 'Hermes 3 is a generalist language model with many improvements over Hermes 2, '
                 'including advanced agentic capabilities, much better roleplaying, reasoning, '
                 'multi-turn conversation, long context coherence, and improvements across the '
                 'board.\n'
                 '\n'
                 'Hermes 3 405B is a frontier-level, full-parameter finetune of the Llama-3.1 405B '
                 'foundation model, focused on aligning LLMs to the user, with powerful steering '
                 'capabilities and control given to the end user.\n'
                 '\n'
                 'The Hermes 3 series builds and expands on the Hermes 2 set of capabilities, '
                 'including more powerful and reliable function calling and structured output '
                 'capabilities, generalist assistant capabilities, and improved code generation '
                 'skills.\n'
                 '\n'
                 'Hermes 3 is competitive, if not superior, to Llama-3.1 Instruct models at '
                 'general capabilities, with varying strengths and weaknesses attributable between '
                 'the two.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/nousresearch/hermes-3-llama-3.1-405b:free',
  'name': 'Nous: Hermes 3 405B Instruct (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'stop',
                           'temperature',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': False,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'nvidia/nemotron-3-nano-30b-a3b:free',
  'best_for': ['agentic-workflows', 'code-generation', 'reasoning'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'nvidia-license'],
  'default_temperature': 0.7,
  'description': 'NVIDIA Nemotron 3 Nano 30B A3B is a small language MoE model with highest '
                 'compute efficiency and accuracy for developers to build specialized agentic AI '
                 'systems.\n'
                 '\n'
                 'The model is fully open with open-weights, datasets and recipes so developers '
                 'can easily\n'
                 'customize, optimize, and deploy the model on their infrastructure for maximum '
                 'privacy and\n'
                 'security.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'moe-model'],
  'max_context_tokens': 256000,
  'missing_syncs': 0,
  'model_id': 'openrouter/nvidia/nemotron-3-nano-30b-a3b:free',
  'name': 'NVIDIA: Nemotron 3 Nano 30B A3B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'seed',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'nvidia/nemotron-3-super-120b-a12b:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'NVIDIA Nemotron 3 Super is a 120B-parameter open hybrid MoE model, activating '
                 'just 12B parameters for maximum compute efficiency and accuracy in complex '
                 'multi-agent applications. Built on a hybrid Mamba-Transformer Mixture-of-Experts '
                 'architecture with multi-token prediction (MTP), it delivers over 50% higher '
                 'token generation compared to leading open models.\n'
                 ' \n'
                 'The model features a 1M token context window for long-term agent coherence, '
                 'cross-document reasoning, and multi-step task planning. Latent MoE enables '
                 'calling 4 experts for the inference cost of only one, improving intelligence and '
                 'generalization. Multi-environment RL training across 10+ environments delivers '
                 'leading accuracy on benchmarks including AIME 2025, TerminalBench, and SWE-Bench '
                 'Verified.\n'
                 ' \n'
                 'Fully open with weights, datasets, and recipes under the NVIDIA Open License, '
                 'Nemotron 3 Super allows easy customization and secure deployment anywhere — from '
                 'workstation to cloud.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 262144,
  'missing_syncs': 0,
  'model_id': 'openrouter/nvidia/nemotron-3-super-120b-a12b:free',
  'name': 'NVIDIA: Nemotron 3 Super (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'response_format',
                           'seed',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'nvidia/nemotron-nano-12b-v2-vl:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'NVIDIA Nemotron Nano 2 VL is a 12-billion-parameter open multimodal reasoning '
                 'model designed for video understanding and document intelligence. It introduces '
                 'a hybrid Transformer-Mamba architecture, combining transformer-level accuracy '
                 'with Mamba’s memory-efficient sequence modeling for significantly higher '
                 'throughput and lower latency.\n'
                 '\n'
                 'The model supports inputs of text and multi-image documents, producing '
                 'natural-language outputs. It is trained on high-quality NVIDIA-curated synthetic '
                 'datasets optimized for optical-character recognition, chart reasoning, and '
                 'multimodal comprehension.\n'
                 '\n'
                 'Nemotron Nano 2 VL achieves leading results on OCRBench v2 and scores ≈ 74 '
                 'average across MMMU, MathVista, AI2D, OCRBench, OCR-Reasoning, ChartQA, DocVQA, '
                 'and Video-MME—surpassing prior open VL baselines. With Efficient Video Sampling '
                 '(EVS), it handles long-form videos while reducing inference cost.\n'
                 '\n'
                 'Open-weights, training data, and fine-tuning recipes are released under a '
                 'permissive NVIDIA open license, with deployment supported across NeMo, NIM, and '
                 'major inference runtimes.',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['image', 'text', 'video'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 128000,
  'missing_syncs': 0,
  'model_id': 'openrouter/nvidia/nemotron-nano-12b-v2-vl:free',
  'name': 'NVIDIA: Nemotron Nano 12B 2 VL (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'seed',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': True},
 {'active': True,
  'api_model_name': 'nvidia/nemotron-nano-9b-v2:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'NVIDIA-Nemotron-Nano-9B-v2 is a large language model (LLM) trained from scratch '
                 'by NVIDIA, and designed as a unified model for both reasoning and non-reasoning '
                 'tasks. It responds to user queries and tasks by first generating a reasoning '
                 'trace and then concluding with a final response. \n'
                 '\n'
                 "The model's reasoning capabilities can be controlled via a system prompt. If the "
                 'user prefers the model to provide its final answer without intermediate '
                 'reasoning traces, it can be configured to do so.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 128000,
  'missing_syncs': 0,
  'model_id': 'openrouter/nvidia/nemotron-nano-9b-v2:free',
  'name': 'NVIDIA: Nemotron Nano 9B V2 (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'response_format',
                           'seed',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'openai/gpt-oss-120b:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'gpt-oss-120b is an open-weight, 117B-parameter Mixture-of-Experts (MoE) language '
                 'model from OpenAI designed for high-reasoning, agentic, and general-purpose '
                 'production use cases. It activates 5.1B parameters per forward pass and is '
                 'optimized to run on a single H100 GPU with native MXFP4 quantization. The model '
                 'supports configurable reasoning depth, full chain-of-thought access, and native '
                 'tool use, including function calling, browsing, and structured output '
                 'generation.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/openai/gpt-oss-120b:free',
  'name': 'OpenAI: gpt-oss-120b (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'seed',
                           'stop',
                           'temperature',
                           'tool_choice',
                           'tools'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'openai/gpt-oss-20b:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'gpt-oss-20b is an open-weight 21B parameter model released by OpenAI under the '
                 'Apache 2.0 license. It uses a Mixture-of-Experts (MoE) architecture with 3.6B '
                 'active parameters per forward pass, optimized for lower-latency inference and '
                 'deployability on consumer or single-GPU hardware. The model is trained in '
                 'OpenAI’s Harmony response format and supports reasoning level configuration, '
                 'fine-tuning, and agentic capabilities including function calling, tool use, and '
                 'structured outputs.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/openai/gpt-oss-20b:free',
  'name': 'OpenAI: gpt-oss-20b (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'seed',
                           'stop',
                           'temperature',
                           'tool_choice',
                           'tools'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'openrouter/free',
  'best_for': ['safe-default', 'free-only-routing'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'The simplest way to get free inference. openrouter/free is a router that selects '
                 'free models at random from the models available on OpenRouter. The router '
                 'smartly filters for models that support features needed for your request such as '
                 'image understanding, tool calling, structured outputs and more. ',
  'image_how': 'depends on the selected free backend',
  'input_modalities': ['text', 'image'],
  'limits': ['free-tier-rate-limited', 'router-picks-backend'],
  'max_context_tokens': 200000,
  'missing_syncs': 0,
  'model_id': 'openrouter/openrouter/free',
  'name': 'Free Models Router',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['frequency_penalty',
                           'include_reasoning',
                           'max_tokens',
                           'min_p',
                           'presence_penalty',
                           'reasoning',
                           'repetition_penalty',
                           'response_format',
                           'seed',
                           'stop',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': False,
  'api_model_name': 'qwen/qwen3-4b:free',
  'best_for': ['fast-classification', 'simple-qa', 'lightweight-reasoning'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'qwen-license'],
  'default_temperature': 0.7,
  'description': 'Qwen3 4B dense via OpenRouter (free). Small but capable. Thinking/non-thinking '
                 'modes. 40 k context.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'compact-model'],
  'max_context_tokens': 40960,
  'missing_syncs': 1,
  'model_id': 'openrouter/qwen/qwen3-4b:free',
  'name': 'Qwen3 4B',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['tools', 'stream', 'reasoning'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'qwen/qwen3-coder:free',
  'best_for': ['code-generation', 'agentic-coding', 'tool-calling', 'debugging'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'qwen-license'],
  'default_temperature': 0.7,
  'description': 'Qwen3-Coder-480B-A35B-Instruct is a Mixture-of-Experts (MoE) code generation '
                 'model developed by the Qwen team. It is optimized for agentic coding tasks such '
                 'as function calling, tool use, and long-context reasoning over repositories. The '
                 'model features 480 billion total parameters, with 35 billion active per forward '
                 'pass (8 out of 160 experts).\n'
                 '\n'
                 'Pricing for the Alibaba endpoints varies by context length. Once a request is '
                 'greater than 128k input tokens, the higher pricing is used.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'moe-model'],
  'max_context_tokens': 262000,
  'missing_syncs': 0,
  'model_id': 'openrouter/qwen/qwen3-coder:free',
  'name': 'Qwen: Qwen3 Coder 480B A35B (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'stop',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'qwen/qwen3-next-80b-a3b-instruct:free',
  'best_for': ['reasoning', 'code-generation', 'multilingual', 'structured-output'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required', 'qwen-license'],
  'default_temperature': 0.7,
  'description': 'Qwen3-Next-80B-A3B-Instruct is an instruction-tuned chat model in the Qwen3-Next '
                 'series optimized for fast, stable responses without “thinking” traces. It '
                 'targets complex tasks across reasoning, code generation, knowledge QA, and '
                 'multilingual use, while remaining robust on alignment and formatting. Compared '
                 'with prior Qwen3 instruct variants, it focuses on higher throughput and '
                 'stability on ultra-long inputs and multi-turn dialogues, making it well-suited '
                 'for RAG, tool use, and agentic workflows that require consistent final answers '
                 'rather than visible chain-of-thought.\n'
                 '\n'
                 'The model employs scaling-efficient training and decoding to improve parameter '
                 'efficiency and inference speed, and has been validated on a broad set of public '
                 'benchmarks where it reaches or approaches larger Qwen3 systems in several '
                 'categories while outperforming earlier mid-sized baselines. It is best used as a '
                 'general assistant, code helper, and long-context task solver in production '
                 'settings where deterministic, instruction-following outputs are preferred.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'moe-model'],
  'max_context_tokens': 262144,
  'missing_syncs': 0,
  'model_id': 'openrouter/qwen/qwen3-next-80b-a3b-instruct:free',
  'name': 'Qwen: Qwen3 Next 80B A3B Instruct (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['frequency_penalty',
                           'max_tokens',
                           'presence_penalty',
                           'response_format',
                           'stop',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_k',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'qwen/qwen3.6-plus-preview:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Qwen 3.6 Plus Preview is the next-generation evolution of the Qwen Plus series, '
                 'featuring an advanced hybrid architecture that improves efficiency and '
                 'scalability. It delivers stronger reasoning and more reliable agentic behavior '
                 'compared to the 3.5 series. In benchmarks, it performs at or above leading '
                 'state-of-the-art models. Designed as a flagship preview, it excels in agentic '
                 'coding, front-end development, and complex problem-solving.\n'
                 '\n'
                 'Note: The model collects prompt and completion data that can be used to improve '
                 'the model. ',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 1000000,
  'missing_syncs': 0,
  'model_id': 'openrouter/qwen/qwen3.6-plus-preview:free',
  'name': 'Qwen: Qwen3.6 Plus Preview (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'presence_penalty',
                           'reasoning',
                           'response_format',
                           'seed',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'qwen/qwen3.6-plus:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'Qwen 3.6 Plus builds on a hybrid architecture that combines efficient linear '
                 'attention with sparse mixture-of-experts routing, enabling strong scalability '
                 'and high-performance inference. Compared to the 3.5 series, it delivers major '
                 'gains in agentic coding, front-end development, and overall reasoning, with a '
                 'significantly improved “vibe coding” experience. The model excels at complex '
                 'tasks such as 3D scenes, games, and repository-level problem solving, achieving '
                 'a 78.8 score on SWE-bench Verified. It represents a substantial leap in both '
                 'pure-text and multimodal capabilities, performing at the level of leading '
                 'state-of-the-art models.',
  'image_how': 'image_url in content array (base64 data-URL or HTTPS URL)',
  'input_modalities': ['text', 'image', 'video'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 1000000,
  'missing_syncs': 0,
  'model_id': 'openrouter/qwen/qwen3.6-plus:free',
  'name': 'Qwen: Qwen3.6 Plus (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'presence_penalty',
                           'reasoning',
                           'response_format',
                           'seed',
                           'structured_outputs',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': True,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': True},
 {'active': True,
  'api_model_name': 'stepfun/step-3.5-flash:free',
  'best_for': [],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': "Step 3.5 Flash is StepFun's most capable open-source foundation model. Built on "
                 'a sparse Mixture of Experts (MoE) architecture, it selectively activates only '
                 '11B of its 196B parameters per token. It is a reasoning model that is incredibly '
                 'speed efficient even at long contexts.',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited'],
  'max_context_tokens': 256000,
  'missing_syncs': 0,
  'model_id': 'openrouter/stepfun/step-3.5-flash:free',
  'name': 'StepFun: Step 3.5 Flash (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 1,
  'supported_parameters': ['frequency_penalty',
                           'include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'stop',
                           'temperature',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False},
 {'active': True,
  'api_model_name': 'z-ai/glm-4.5-air:free',
  'best_for': ['agentic-workflows', 'reasoning', 'tool-calling'],
  'compliance': ['openrouter-tos', 'free-tier', 'api-key-required'],
  'default_temperature': 0.7,
  'description': 'GLM-4.5-Air is the lightweight variant of our latest flagship model family, also '
                 'purpose-built for agent-centric applications. Like GLM-4.5, it adopts the '
                 'Mixture-of-Experts (MoE) architecture but with a more compact parameter size. '
                 'GLM-4.5-Air also supports hybrid inference modes, offering a "thinking mode" for '
                 'advanced reasoning and tool use, and a "non-thinking mode" for real-time '
                 'interaction. Users can control the reasoning behaviour with the `reasoning` '
                 '`enabled` boolean. [Learn more in our '
                 'docs](https://openrouter.ai/docs/use-cases/reasoning-tokens#enable-reasoning-with-default-config)',
  'image_how': 'not supported - text-only model',
  'input_modalities': ['text'],
  'limits': ['free-tier-rate-limited', 'moe-model'],
  'max_context_tokens': 131072,
  'missing_syncs': 0,
  'model_id': 'openrouter/z-ai/glm-4.5-air:free',
  'name': 'Z.ai: GLM 4.5 Air (free)',
  'output_modalities': ['text'],
  'pdf_how': 'extract text and send as message content',
  'seen_syncs': 2,
  'supported_parameters': ['include_reasoning',
                           'max_tokens',
                           'reasoning',
                           'temperature',
                           'tool_choice',
                           'tools',
                           'top_p'],
  'supports_images': False,
  'supports_pdf': False,
  'supports_reasoning': True,
  'supports_streaming': True,
  'supports_tools': True,
  'supports_video': False}]
